export const FIELD_LABELS: Readonly<Record<string, string>> = {
  ho_ten: 'Họ và tên',
  gioi_tinh: 'Giới tính',
  ngay_sinh: 'Ngày sinh',
  so_cccd: 'Số CCCD/CMND hiện tại',
  ngay_cap_cccd: 'Ngày cấp CCCD/CMND',
  co_quan_cap_cccd: 'Cơ quan/nơi cấp CCCD/CMND',
  so_dien_thoai_di_dong: 'Số điện thoại di động',
  email: 'Địa chỉ email',
  tinh_trang_hon_nhan: 'Tình trạng hôn nhân',
  trinh_do_hoc_van: 'Trình độ học vấn',
  hinh_thuc_so_huu_nha: 'Hình thức sở hữu nhà đang ở',
  dia_chi_thuong_tru: 'Địa chỉ thường trú',
  dia_chi_hien_tai: 'Địa chỉ nơi ở hiện tại',
  thoi_gian_cu_tru_hien_tai: 'Thời gian cư trú tại địa chỉ hiện tại',
  so_tien_vay_de_nghi: 'Số tiền vay đề nghị bằng số',
  so_tien_vay_de_nghi_bang_chu: 'Số tiền vay đề nghị bằng chữ',
  ngay_lam_don: 'Ngày làm đơn',
  ky_han_vay: 'Kỳ hạn vay đề nghị',
  muc_dich_vay: 'Mục đích vay',
  chi_tiet_muc_dich_vay_khac: 'Chi tiết mục đích vay khác',
  phuong_thuc_giai_ngan: 'Phương thức giải ngân',
  loai_tai_khoan_nhan_giai_ngan: 'Loại tài khoản nhận giải ngân',
  ngan_hang_nhan_giai_ngan: 'Ngân hàng nhận giải ngân',
  chi_nhanh_nhan_giai_ngan: 'Chi nhánh/PGD nhận giải ngân',
  so_tai_khoan_nhan_giai_ngan: 'Số tài khoản nhận giải ngân',
  ten_chu_tai_khoan_nhan_giai_ngan: 'Tên chủ tài khoản nhận giải ngân',
  nghe_nghiep_chuyen_mon: 'Nghề nghiệp/chức danh chuyên môn',
  ten_don_vi_cong_tac: 'Tên công ty/đơn vị công tác',
  ma_so_thue_cong_ty: 'Mã số thuế công ty',
  dia_chi_cong_ty: 'Địa chỉ công ty',
  dien_thoai_cong_ty: 'Điện thoại công ty',
  chuc_vu: 'Chức vụ',
  loai_hop_dong_lao_dong: 'Loại hợp đồng lao động',
  ngay_bat_dau_lam_viec: 'Ngày bắt đầu làm việc',
  ngay_nhan_luong_hang_thang: 'Ngày nhận lương hàng tháng',
  muc_luong_gross: 'Mức lương gross',
  thu_nhap_thuc_lanh_hang_thang: 'Thu nhập thực lãnh hàng tháng',
  chi_phi_sinh_hoat_hang_thang: 'Chi phí sinh hoạt hàng tháng',
  hinh_thuc_nhan_luong: 'Hình thức nhận lương',
  so_nguoi_phu_thuoc: 'Số người phụ thuộc tài chính',
}

export function getFieldLabel(fieldCode: string): string {
  return FIELD_LABELS[fieldCode] ?? fieldCode
}
